# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b6fcb81028556c282105ef2b7aebbb7216690309fd9f2046695969791b6b63c9ac4b3c0883eef91eaff051964890375d0c05a79a420e123ac3ee29c4826fc27

test:
  secret_key_base: 9dc3c7c4c7d8c9872569301fe0d9ad9164dca8eb6678b32e05307ebacb54c18b867b3ed132720f4bc1a2d1e616ffd40b889b329e1f8d217432f8b26a808f946c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
